### ISSUE TITLE
[FEATURE] A video showing how to use UAR

### ISSUE THREAD

**Issue by sdfdger** [Skyluker4/UnityAssetReplacer#13]
## Problem

I'm trying to use this and I'm getting this error `System.NullReferenceException: Object reference not set to an instance of an object.` with this command `unityassetreplacer -b="C:\path\to\folder\assets\bin\Data\sharedassets3.assets" -m="Visor" -d="C:\path\to\folder\dump"`. Visor is the name of an asset I found using UABEA.

## Solution

A video showing how to use this would be very helpful.

## Alternatives

UABE, doesn't work on the new unity
UABEA, crashes when trying to replace or export files
UAAE, broken

## Additional Context

I'm on Windows 10

**Comment by Skyluker4** [comment]
That's a good idea. I'll work on that later this week.

**Comment by Skyluker4** [comment]
Sorry it took so long, I got busy after recording the video. If there's something missing, reopen the issue.
