### ISSUE TITLE
Clear Examples

### ISSUE THREAD

**Issue by GalaxyDJx** [Skyluker4/UnityAssetReplacer#6]
I am really unsure on what "members" are supposed to mean. GameObjects, the name of the GameObject.. doesn't work

I would like a more clear example of what member I'm supposed to type or a list of members I could use

**Comment by Skyluker4** [comment]
Sorry for not getting to this sooner. I'll be updating the documentation here in the next couple of weeks. I agree that the documentation and examples need to be more clear.

**Comment by Skyluker4** [comment]
Okay, I updated the README. If there are any more problems, let me know.
